<?php
include_once("_inc/assets/register_assets.php");
include_once("_inc/taxonimies/blog_taxonomy.php");
include_once("helper/helper.php");
include_once("_inc/meta-box/pages-metabox.php");
include_once("_inc/meta-box/template-setting.php");
include_once("_inc/meta-box/belog-metabox.php");
include_once("_inc/jdf-jalali/jdf.php");
include_once("_inc/cy-theme-comment-body/cy_theme_comment_body.php");
include_once("_inc/cy-theme-comment-body/comment-form.php");
include_once("_inc/nav-menu/nav-menu-setup-theme.php");
